Feature/add optax scheduler
rodrigonogueira4/t5x pull request #6
Opened 2022-11-12 20:27 UTC by piresramon

- Rename gin file.
- Add scheduler (for now, using the same arguments used for training gptimbau)
- Set vocab size as 50304 (multiple of 128 for TPU efficiency)

2022-11-12 22:30 UTC, rodrigonogueira4 approved these changes
Muito obrigado por enviar esse codigo

2022-11-12 22:44 UTC, ZanezZephyrs requested changes

2022-11-12 22:44 UTC, ZanezZephyrs commented on t5x/examples/decoder_only/examples/base_mc4_from_scratch.gin
> +  decay_steps = 135518  %TRAIN_STEPS
esse %train_steps era pra ser um comentario, certo? acho que deveria ser # train_steps.

Tentei rodar com essa config e deu erro por causa disso.

2022-11-13 11:36 UTC, piresramon commented on t5x/examples/decoder_only/examples/base_mc4_from_scratch.gin
> +  decay_steps = 135518  %TRAIN_STEPS
Verdade, @ZanezZephyrs. Obrigado!

2022-11-13 11:42 UTC, piresramon commented on t5x/examples/decoder_only/examples/base_mc4_from_scratch.gin
> +  decay_steps = 135518  %TRAIN_STEPS
Deixei o %TRAIN_STEP na frente (agora comentado) caso optemos por fazer o decay até o final do treino (o GPT-J fez até perto do fim).

2022-11-14 11:30 UTC, merged